<?php

use App\ViewHelpers\CompletedTodosViewHelper;

?>
<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        a {
            text-decoration: none;
            color: #719e40;
        }

        a:hover {
            color: #aaa;
        }

        }
    </style>
</head>
<body>
    <h1>Completed Todos</h1>
    <form action="/completed-todos">
        <input type="search" name="searchString" />
        <button type="submit">Search Todos</button>
        <a href="/completed-todos">Clear Search</a>
    </form>
    <?= CompletedTodosViewHelper::seeAllCompletedTodos($completedTodos) ?>
    <div>
        <a href="/">See todos to do</a>
    </div>
</body>
</html>
