<?php

?>
<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 0 auto;
            width: 60%;
            padding: 0;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }

        a {
            text-decoration: none;
            color: #719e40;
        }

        a:hover {
            color: #aaa;
        }

    </style>
</head>
<body>
<h1>Edit Todo</h1>

<form method="post" action="/update-todo/<?=$todo['id']?>">
    <input type="text" name="todoString" placeholder="<?=$todo['to-do']?>" />
    <button type="submit">Update Todo</button>
    <a href="/">Clear Search</a>
</form>

</body>
</html>
