<?php
use App\ViewHelpers\TodosViewHelper;
?>

<!DOCTYPE html>
<html lang="en-GB">
<head>
    <meta charset="utf-8"/>
    <title>Slim 4</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>

    <style>
        body {
            padding: 0;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            color: #aaa;
            font-size: 18px;
            background-color: #fbfbfb;
        }

        section {
            display: flex;
            flex-flow: column;
            align-items: center;
        }

        table{
            margin: 0 auto;
        }

        h1 {
            color: #0aa39c;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 50px;
            font-weight: 200;
            text-align: center;
            margin: 20px;
        }

        p {
            margin: 10px;
        }

        .edit {
            text-decoration: none;
            background-color: #0aa39c;
            color: #fbfbfb;
            padding: 5px 10px;
            margin: 0 10px;
            border-radius: 3px;
        }

        .edit:hover {
            color: #f8a503;
        }

        a {
            margin: 10px;
            color: #0aa39c;
            text-decoration: none;
        }

    div {
        display: flex;
        justify-content: center;
    }

    button {
        width: 100px;
    }

    </style>

</head>
<body>
    <h1>To Do List</h1>
    <section>
        <form method="post" action="/add-todo">
            <input type="text" name="textInput" />
            <button type="submit">Add To Do</button>
        </form>
        <form action="/">
            <input type="search" name="searchString" />
            <button type="submit">Search Todos</button>
        </form>
            <a href="/">Clear Search</a>
    </section>
    <table>
    <?= TodosViewHelper::seeAllTodos($todos) ?>
    </table>
    <div>
        <a class="pageLink" href="/completed-todos">See completed todos</a>
    </div>
</body>
</html>
